services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./services/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  api:
    build: ./services/api
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./services/api/app:/app/app
    env_file: .env
    depends_on:
      - mqtt
    restart: unless-stopped

  telemetry:
    build: ./services/telemetry
    container_name: telemetry
    ports:
      - "8003:8003"
    volumes:
      - rescue-data:/data
      - ./services/telemetry/app:/app/app
    env_file: .env
    depends_on:
      - mqtt
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    restart: unless-stopped

  ollama-pull-model:
    image: curlimages/curl:latest
    container_name: ollama-pull-model
    depends_on:
      - ollama
    entrypoint: >
      /bin/sh -c "
      echo 'Attente du démarrage du serveur Ollama...';
      until curl -s http://ollama:11434/api/tags > /dev/null; do sleep 2; done;
      echo 'Ollama est pret ! Telechargement de phi4-mini...';
      curl -s -N -X POST http://ollama:11434/api/pull -d '{\"name\": \"phi4-mini\"}';
      echo 'Modele installe avec succes !';
      "
    restart: "no"

  llm:
    build: ./services/llm
    container_name: llm
    ports:
      - "8001:8001"
    volumes:
      - ./services/llm/app:/app/app
    env_file: .env
    depends_on:
      - ollama
    restart: unless-stopped

  frontend:
    build: ./services/frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
    environment:
      - VITE_DROIDCAM_URL=http://192.168.1.15:4747/video
    depends_on:
      - api
    restart: unless-stopped

volumes:
  rescue-data:
  ollama_storage:
